apiVersion: v1
kind: Pod
metadata: 
    name: ali-pod-ollama-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A10
            - NVIDIA-A6000
            - NVIDIA-GeForce-RTX-3090
            - NVIDIA-GeForce-RTX-2080-Ti
            - NVIDIA-TITAN-RTX
            - NVIDIA-RTX-A5000
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/smatous/ollama_datasets
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: 1
      requests:
        memory: 32Gi
        cpu: 16
        nvidia.com/gpu: 1